tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#2d3435",
        "primary-container": "#d4e3ff",
        "tertiary": "#595e78",
        "primary-dim": "#00539a",
        "on-primary-container": "#005299",
        "on-secondary-fixed": "#33414a",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#dadefe",
        "on-tertiary-fixed-variant": "#545873",
        "error-container": "#fe8983",
        "tertiary-dim": "#4d526c",
        "on-background": "#2d3435",
        "on-error": "#fff7f6",
        "surface-dim": "#d3dbdd",
        "outline-variant": "#acb3b4",
        "surface-tint": "#005faf",
        "on-primary": "#f6f7ff",
        "surface-container": "#ebeeef",
        "error-dim": "#4e0309",
        "on-secondary-fixed-variant": "#4f5d67",
        "surface-variant": "#dde4e5",
        "inverse-primary": "#4e9af9",
        "error": "#9f403d",
        "surface-container-highest": "#dde4e5",
        "secondary-fixed": "#d6e5ef",
        "on-primary-fixed": "#004079",
        "background": "#f9f9f9",
        "secondary-dim": "#47555e",
        "secondary": "#53616a",
        "on-primary-fixed-variant": "#005caa",
        "on-error-container": "#752121",
        "outline": "#757c7d",
        "primary": "#005faf",
        "surface-bright": "#f9f9f9",
        "on-secondary-container": "#46545d",
        "tertiary-fixed-dim": "#ccd0ef",
        "secondary-container": "#d6e5ef",
        "inverse-surface": "#0c0f0f",
        "primary-fixed": "#d4e3ff",
        "on-tertiary": "#faf8ff",
        "on-tertiary-fixed": "#383c55",
        "on-secondary": "#f4faff",
        "surface": "#f9f9f9",
        "primary-fixed-dim": "#bdd6ff",
        "on-surface-variant": "#596061",
        "inverse-on-surface": "#9c9d9d",
        "tertiary-fixed": "#dadefe",
        "surface-container-low": "#f2f4f4",
        "on-tertiary-container": "#4a4f69",
        "secondary-fixed-dim": "#c8d6e1",
        "surface-container-high": "#e4e9ea"
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"]
      },
      borderRadius: { DEFAULT: "0px", lg: "0px", xl: "0px", full: "0px" }
    }
  }
};
